<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lg.platform.loyalty</groupId>
        <artifactId>lg5-loyalty-ledger</artifactId>
        <version>1.0.0-alpha</version>
    </parent>
    <artifactId>lg5-loyalty-ledger-domain</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>lg5-loyalty-ledger-application-service</module>
        <module>lg5-loyalty-ledger-domain-core</module>
    </modules>
</project>
